name: student
version: 1.0.0+1
publish_to: none
description: Doplus app for student
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_sliding_drawer: ^2.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  pie_chart: ^5.4.0
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  connectivity_plus: ^5.0.2
  lottie: ^2.7.0
  app_settings: ^5.1.1
  flutter_local_notifications: ^16.2.0
  firebase_analytics: ^10.7.1
  permission_handler: ^10.4.5
  package_info_plus: ^4.2.0
  dropdown_button2: ^2.3.9
  pdf: ^3.10.6
  path_provider: ^2.1.1
  open_file: ^3.3.2
  printing: ^5.11.1
  url_launcher: ^6.2.1
  video_thumbnail: ^0.5.3
  video_player: ^2.8.1
  video_player_control_panel: ^1.1.1
  voice_message_package: ^2.1.2
  amplify_flutter: ^1.6.1
  amplify_storage_s3: ^1.6.1
  amplify_auth_cognito: ^1.6.1
  record: ^5.0.1
  another_audio_recorder: ^1.1.0
  file_picker: ^6.1.1
  faker: ^2.1.0
  sticky_az_list: ^0.0.7
  cached_network_image: ^3.2.3
  gradient_icon: ^2.0.9
  animated_text_kit: ^4.2.2
  animated_typing: ^0.2.1
  expansion_tile_group: ^1.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dopluserp_logo.png"

